/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/modals/org.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function Avatar2(props) {
  const group = useRef();
  const avatar = useGLTF("modals/sitpointing.glb");
  console.log(avatar);
  const { actions, names } = useAnimations(avatar.animations, avatar.scene);
  useEffect(() => {
    actions[names].reset().play();
    console.log(actions[names]);
    return () => {
      actions[names].reset().fadeOut();
    };
  }, [avatar.animations]);
  return (
    <group>
      <primitive object={avatar.scene} />
    </group>
  );
}

useGLTF.preload("modals/sitpointing.glb");
