/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/modals/Scene4.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";

export function Avatar(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("modals/Scene4.gltf");
  const { animations: standingAnimation } = useFBX("animations/Standing.fbx");
  standingAnimation[0].name = "Standing";
  const { actions } = useAnimations(standingAnimation, group);

  useEffect(() => {
    actions["Standing"].reset().play();
    // console.log(actions);
  }, []);
  return (
    <group {...props}>
      <group ref={group} dispose={null}>
        <mesh
          geometry={nodes.EyeLeft.geometry}
          material={materials.Wolf3D_Eye}
        />
        <mesh
          geometry={nodes.EyeRight.geometry}
          material={materials.Wolf3D_Eye}
        />
        <mesh
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Wolf3D_Skin}
        />
        <mesh
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Wolf3D_Teeth}
        />
        <mesh
          geometry={nodes.Wolf3D_Hair.geometry}
          material={materials.Wolf3D_Hair}
        />
        <mesh
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Wolf3D_Body}
        />
        <mesh
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Wolf3D_Outfit_Bottom}
        />
        <mesh
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
        />
        <mesh
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Wolf3D_Outfit_Top}
        />
      </group>
    </group>
  );
}

useGLTF.preload("modals/Scene4.gltf");
